AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0
  Exclude:
    - '.bundle/**/*'
    - 'schema/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true
